### PR TITLE
Add slider block and update event content type

### PR DESCRIPTION
**Pull request by iFlameing**

### CODE REVIEW

**Comment by davisagli** [comment]
@sneridagh @ericof @iFlameing Can we convert this to use plone.exportimport? I can't review a pull request that has 30k additions and subtractions in a single file in any useful way. The fact that there are so many changes has me concerned that this changes more than we intended.

**Comment by ericof** [comment]
Yes, this should be a new PR

**Comment by iFlameing** [comment]
@davisagli I can guarantee that it only consist the slider and event changes. We have this much changes just of styling. when I save file my file is completely different than which is present here. That's why we have that much line changes.

**Comment by iFlameing** [comment]
@davisagli https://github.com/kitconcept/kitconcept.voltolighttheme/pull/35

**Pull request closed without merging**
